### ISSUE TITLE
Missing GetDirectoryList()

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#13]
Version: Minisphere 1.0

Sphere 1.5+ had this API method to return a string of folder names in a directory. I use it for save game management in a few of my games.

**Comment by fatcerberus** [comment]
Duly noted - I will add this for 1.0.1.  I thought I was missing one of these functions... I implemented GetGameList and GetFileList, but forgot this one, go figure. :-)

**Comment by fatcerberus** [comment]
Fixed. :-)
