### ISSUE TITLE
Rewrite README.md

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#134]
The introduction in particular reflects the early stages of the project when it was primarily an enhanced Sphere 1.x substitute.  Now that miniSphere has become the *de facto* Sphere 2.0--with legacy compatibility as a nice footnote at best--that text is no longer representative of the project's goals.

It'd probably be good at the same time to expand the SSJ and Cell sections as well, especially now that Cell has become such a cornerstone of the toolchain.

Important features to mention:
- [x] ECMAScript 6 support
- [x] Sphere v2 API + miniRT
- [x] Cell
- [x] SSJ/SSJ Blue
- [x] 🐗 **\*MUNCH\***

**Comment by fatcerberus** [comment]
The only thing that remains is to write something about the Sphere v2 API, perhaps with some code snippets.

**Comment by MIfeanyi** [comment]
What would be the best place for someone to go to find the differences and work on this?

**Comment by fatcerberus** [comment]
Not sure I follow; differences between what?

**Comment by MIfeanyi** [comment]
V2 API & 1.x

**Comment by fatcerberus** [comment]
I guess the best bet would be to compare:
* v1 - https://github.com/sphere-group/sphere/blob/master/sphere/docs/development/api.txt
* v2 - https://github.com/fatcerberus/minisphere/blob/master/docs/sphere2-api.txt

**Comment by fatcerberus** [comment]
Showstopper for 5.0.0; `README.md` is now out of date thanks to the switch from Duktape to ChakraCore and the new focus on the event loop.

**Comment by fatcerberus** [comment]
:pig_nose: **\*MUNCH\***
