### ISSUE TITLE
IsKeyPressed() doesn't recognize right-side Shift/Ctrl/Alt

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#20]
In Sphere ctrl, shift, and alt work the same on either side of the keyboard. In minisphere only the left half ever works.

**Comment by fatcerberus** [comment]
This is a known issue, actually.  It has to do with Allegro differentiating the left and right keys, while Sphere conflates them.  I've been meaning to fix it for a while now, but never got around to it.  Chalk up another fix for 1.0.10!

**Comment by fatcerberus** [comment]
Fixed in master.
