### ISSUE TITLE
Fix initialization failure after calling ExecuteGame()

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#225]
On non-Windows platforms, the engine fails to reinitialize correctly after an `ExecuteGame()` call.  My suspicion is that ChakraCore doesn't like the engine disposing the JS runtime handle and immediately creating a new one.

Look into the cause of the failure.

**Comment by rhuanjl** [comment]
I had a quick look, the error point is in JsCreateContext within jsal_init - perhaps surprisingly not in JSCreateRuntime; as for the cause of the error I don't know.

My best guess is that the previous runtime hasn't finished closing down and there's some left over detritus from it that the new Context sees instead of seeing the clean new run time.

**Comment by fatcerberus** [comment]
Thanks, I actually looked into this with GDB a few days ago; the point of failure is indeed `JsCreateContext()`, specifically it returns `JsErrorWrongThread`.  My theory is that it gets confused because I’m longjmp’ing back into `main` during JS handling and Chakra still thinks there’s a call in progress on the thread so doesn’t allow making a new context.

I’ll need to look into whether there’s a way to completely bail out of JS without a longjmp.

**Comment by rhuanjl** [comment]
Per discussion in this issue when you call the helper threads (GC and compiler) don't close down immediately when a context is discard so I wouldn't be at all surprised if the issue is detritus they have left around https://github.com/Microsoft/ChakraCore/issues/3700

**Comment by fatcerberus** [comment]
Fixed in master, calling `ExecuteGame()` will now, instead of directly issuing a longjmp, disable JavaScript execution which allows control to return to `main()` naturally.  At that point the uninit-init cycle works without producing weird errors, and switching games goes off without a hitch.
