### ISSUE TITLE
Deprecate some API functions ahead of the mS 5.0 freeze

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#234]
The aim is for miniSphere 5.0 to lock down the Core API, with no breaking changes allowed to existing APIs after that point.  However, now that `async`/`await` and promises are first-class citizens, I'm thinking it would be wise to deprecate functions dedicated to the old way of doing things, so as not to catch them in the API freeze and then never be able to remove them.

The following is old-style Sphere logic and will cause problems by blocking the event loop:
```js
while (true)
{
    /* update some stuff here */

    /* render stuff here */

    screen.flip();
}
```

While events and promises will fire with this code, they will do so from a non-empty callstack which violates the assumptions intrinsic to async workflows: promises in particular are expected to settle only after the callstack unwinds and control returns to the event loop.  Furthermore, the above code would never work in [Oozaru](https://github.com/fatcerberus/oozaru) since browsers don't like blocking code and will forcibly terminate the script if it does this.  Given all that, it makes most sense to steer people away from the above construct by deprecating all the APIs that can be used to implement it, to be completely removed in a future release.

Functions to be deprecated:
- [x] `Sphere.run()`: Performs an event loop tick synchronously.  This has a few uses even if the game doesn't block indefinitely; however no such construct exists in Web JavaScript so this would be a challenge to implement there.  It also suffers from the issue described above: Promises will settle from a non-empty callstack.  Best to remove it from the equation.
- [x] `Sphere.exit()`: Forcibly exits the game by performing a longjmp into `main()`, which then shuts down the engine.  This is not the cleanest way to exit especially in the presence of an event loop and a modern JIT'd JavaScript engine.  `Sphere.shutDown()` will be the recommended way to exit going forward.
- [x] `screen.flip()`: The event loop handles this automatically.  If blocking the event loop is not allowed and `Sphere.run()` is also removed, there's no reason for this to exist either.

Functions excluded from the API freeze:
- [x] `Sphere.restart()`: Same issue as above, this is implemented with a longjmp which is even *more* problematic than `Sphere.exit()` since the event loop is started anew without actually restarting the engine process, potentially introducing memory leaks.
- [x] `Sphere.sleep()`: Doesn't need to be removed, but should be implemented with a promise instead of blocking.

**Comment by fatcerberus** [comment]
`Sphere.shutDown()` has been added in master which cancels everything, including update and render jobs, signaling the event loop to unwind.  As such `Sphere.exit()` can be moved to the “deprecate” list.

**Comment by fatcerberus** [comment]
Hmm... thinking about this some more, miniSphere 5.0 *is* a semver-major release and these are Sphere v2 APIs.  Maybe it would be wise to simply remove or refactor them now.  Deprecation seems like an unnecessary step when I’ve already made breaking changes to the API, sometimes fairly substantial ones, elsewhere.

**Comment by rhuanjl** [comment]
screen.flip() is very useful for certain quick tests - mocking something up, testing out some functionality etc. I agree it's a bad idea in any kind of finished product in the "event loop world".

I agree on the other ones.

**Comment by fatcerberus** [comment]
`Sphere.exit` and `Sphere.run` have been removed in master; `Sphere.sleep` was changed to return an awaitable promise that resolves when the delay expires rather than blocking.

`screen.flip` remains callable for now, but is no longer documented.

**Comment by fatcerberus** [comment]
`Sphere.restart()` is the last function that needs to be changed.  It's still implemented via longjmp in master.

**Comment by fatcerberus** [comment]
Fixed in master.  End result:
* `Sphere.run()` and `screen.flip()` were removed from the API
* `Sphere.exit()` was reworked into `Sphere.shutDown()` to avoid a messy longjmp.
* `Sphere.restart()` no longer performs a longjmp and instead relies on the event loop to trigger the restart.
