### ISSUE TITLE
Add proper constructors and properties to Sphere objects

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#24]
How should these be implemented?  That is, do I require all constructors to be called via `new` (this is my preference), or do I allow them to called as bare functions, like so:

``` javascript
var red = Color(255, 0, 0, 255);
```

**Comment by fatcerberus** [comment]
So I've decided that since I'm adding proper constructors, I might as well add proper properties.  As with `LoadImage()` etc., the old getter and setter methods will remain for backwards compatibility, but you will now be able to do stuff like this in new games:

``` javascript```
var sound = LoadSound('cows_eat_kitties.wav');
var soundLen = sound.length;
sound.volume = 0.1;  // so the kitties don't hear the cow coming...
```

**Comment by FlyingJester** [comment]
You can see how TurboSphere does it at:
https://github.com/FlyingJester/TurboSphere/wiki/Function-List
For the most part, I just used the argument types for the functions the Load/Create functions. For Surfaces/Images, both the capabilities of LoadSurface and CreateSurface are in the constructor, distinguished by the number and types of arguments.
I've found this to work quite well.

**Comment by fatcerberus** [comment]
From what I can gather, TurboSphere allows the constructors to be called bare, i.e.

``` javascript
var sound = Sound("Munch.wav");
```

I'm not sure I like that; mainly because I intuitively expect `Color(0, 0, 0) === Color(0, 0, 0)` to evaluate to true, when in fact it ends up false because I've created two separate objects.  Kind of an OCD thing I guess, but eh.

**Comment by FlyingJester** [comment]
It shouldn't let that happen. I'm using SM's default constructor behaviour, in which I am actually defining a type rather than a constructor in particular. This automates setting up the prototype chain, and _should_ make the constructor a true constructor, which is slightly different than a normal function (in other ways than what you demonstrate, too).

**Comment by fatcerberus** [comment]
Ah, you might want to clarify that in the documentation you linked then.  For constructors, it specifies the signature as ObjectName(arg1, arg2...), implying that you call it as any other function.  It would be clearer I think if you added `new` to the signature.

**Comment by fatcerberus** [comment]
The big four are done: Images, Surfaces, Sounds and Colors.  Anyone that wants to test it out, check out the `add-object-constructors` branch. :smile:

https://github.com/fatcerberus/minisphere/tree/add-object-constructors

@FlyingJester: I implemented the Image and Surface constructors identically to what's in your TurboSphere function list.  With one enhancement: The Surface constructor will accept an image object.  `Image:createSurface()` is still a thing, but I figured since the Image constructor can accept a Surface, the reverse should also be true.

**Comment by fatcerberus** [comment]
So, having just implemented the Socket constructor, I realized I don't much like the conflation of listening sockets with I/O sockets after all, so I'm going to add a ListeningSocket a la TS, and may also rename the Socket constructor to `IOSocket`.

I will keep `ListenOnPort()` and `OpenAddress()` with their old Sphere-compatible behavior, of course.  They will create a `LegacySocket`.

**Comment by fatcerberus** [comment]
Done and merged. :dancer:  This was a lot of fun to implement! :smile:

I'm thinking I'll release a beta version (1.1b1) with the new constructors, as it involved a ton of refactoring and I'd be very surprised if I didn't break _something_ in the process.
