### ISSUE TITLE
Add an API for dealing with images in Cell

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#249]
It would be nice to be able to work directly with images at the pixel level in Cellscript modules, to support, e.g. spriteset generation and the like.  Add an API to support this, either as a standard library module or maybe even built in.

**Comment by rhuanjl** [comment]
All I'm looking for is .png -> array of pixel data loading/conversion - my PixelBuffer.mjs routines can do all the manipulation necessary after the data is loaded.

**Comment by fatcerberus** [comment]
This is implemented experimentally in the [`cell-png-support`](https://github.com/fatcerberus/minisphere/tree/cell-png-support) branch.  It'll be merged into master once I figure out how to get Travis to build it successfully...

**Comment by fatcerberus** [comment]
Support for the `Image` class in Cellscripts is now available in master.  It turns out libpng 1.6 is source-compatible with 1.2 as long as you don't access the members of the the png_struct directly (which has never been officially supported), and the 1.2 API isn't quite as bad as I originally thought.

I'll give the API some thought prior to miniSphere 5.2.0 release, but otherwise this is complete.
