### ISSUE TITLE
Add support for getting eaten by the pig 🐽

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#259]
Add a new API function called `Summon.callPig()`.  If you call it, it summons the pig.  And then you get eaten by it.

**Comment by fatcerberus** [comment]
This feature needs to be implemented, like, yesterday.  Anyone around here know any time travelers?

**Comment by rhuanjl** [comment]
I travel through time slowly - though only forwards, is that any help?

**Comment by fatcerberus** [comment]
Not particularly in this instance, no.

**Comment by fatcerberus** [comment]
Adding this feature will probably cause everyone to get eaten by the pig even if they don't actually call the new API (because the pig is super-hungry), so closing as impractical.
