### ISSUE TITLE
Always use full sandbox enforcement for SPK packaged games

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#265]
In order to ease development and allow quick prototyping, it is possible to disable the SphereFS sandbox by including `sandbox: 'none'` in the game manifest.  Doing so enables full read and write access to all files on the system through an absolute path.

Unfortunately, because the setting is honored in production even for a packaged game, this makes SPK a potentially dangerous format.  A malicious package could freely corrupt or delete files on a user’s system just by having its sandbox disabled.

Ideally SPK should be safe; to that end it might make sense to either:
* Force the sandbox mode to `full` when running a game from a package.  This is nice, as the developer doesn’t need to take any additional action to secure the code: it would automatically be secure by virtue of being a package.
* Always use a `full` sandbox in production but allow it to be relaxed under SpheRun, even for a package.  This is easier to explain, but doesn’t fully solve the “malicious game package” issue.  Then again, one would expect devopers to be smart enough not to run strange code...

Not sure which solution is ultimately better yet.

**Comment by rhuanjl** [comment]
How does the sandbox interact with the v1 APIs?

**Comment by fatcerberus** [comment]
For compatibility reasons, `~/` to a v1 function means “the directory containing the manifest” and is *always writable*—even when running from an SPK, in which case the write is virtualized by redirecting it to somewhere within the user’s home directory (this virtualization isn’t unique to miniSphere, S1.5 did it as well).

I *think* SphereFS prefixes other than `~/` are legal when used with a v1 function, in which case they follow the usual sandboxing rules.

**Comment by rhuanjl** [comment]
Per Sphere 1.5 api documentation "/" was meant to be the directory containing Sphere.exe - and was also writeable.

There wasn't meant to be anyway to go outside of the Sphere directory but you could in theory delete/edit Sphere with a v1 game.

**Comment by fatcerberus** [comment]
Huh, didn’t know that.  I don’t think we should emulate that behavior. :smile:

**Comment by rhuanjl** [comment]
I think some old Sphere v1 demos used "/system/" prefixed paths to access the system folder to load resources there directly.

Sphere v1 had no writeable/non-writeable distinction but did at least have the restriction that you (in theory) could only access: 1. your game's folder AND 2. the Sphere folder and nowhere else.

**Comment by fatcerberus** [comment]
Yeah, it was a heavily sandboxed engine.  The ability to access the directory containing the engine executable unrestricted almost seems like an oversight, considering the degree of lockdown in general.

It’s just weird because when I reverse-engineered the Sphere 1.x sandbox I could have sworn anything starting with `/` was a sandbox violation (“invalid path”)... maybe I’m misremembering.

**Comment by fatcerberus** [comment]
As this is an important security issue, I'm moving this up to 5.3.  Unfortunately I haven't decided on a solution yet, but the 5.3.0 release seems to be a ways off still, so time is still on my side.

**Comment by fatcerberus** [comment]
This issue is dealt with in the above commit.  Full sandbox enforcement will be enabled in production (i.e. when run with `minisphere`) regardless of the sandboxing mode in the manifest.

Since the `sandboxing` mode is now only honored in SpheRun (the first such manifest field of its kind), it has been moved into a new `development` namespace set aside for this purpose.  As I figure devs might forget about this, when building with `cell build --release`, Cell will warn if a non-default sandboxing mode is enabled for the project and that it will be ignored in production.
