### ISSUE TITLE
Mouse#getEvent does not account for scaling

### ISSUE THREAD

**Issue by postcasio** [spheredev/neosphere#271]
Unlike `Mouse#x` and `Mouse#y`, `Mouse#getEvent` does not account for the screen's scaling meaning its `x` and `y` properties are consistently double the correct value (on a 2x screen)

**Comment by fatcerberus** [comment]
Thanks, good catch.  It also doesn't account for the letterbox offset, meaning the values in fullscreen are likely to be way off the mark no matter what.

As there are no API calls to get the current scaling and offsets, I don't think it will be possible to work around this in JS.  I'll get right on fixing it.

**Comment by fatcerberus** [comment]
Hmm, this is tricky to fully fix without invasive refactoring.  Some background: internally, `.x` and `.y` are handled through the internal `screen_t` class, which knows all about screen scaling, etc. and can easily correct the cursor position on the fly.  `getEvent` on the other hand, is managed directly by the input subsystem which has no knowledge of anything to do with `screen_t`.  This is both the cause of the bug, and also what makes it tricky to fix.

There's an easy hack I can do whereby the correction would be applied at the time `getEvent` is called.  This would work well except in the case where a game is switched between fullscreen or windowed at runtime, whereupon any mouse events that were in the queue before this point would return incorrect coordinates.  This is not ideal, but it is a strict improvement over the current situation (where the coordinates are never correct) so I might just implement it anyway.

**Comment by fatcerberus** [comment]
Fixed (sort of) by https://github.com/fatcerberus/minisphere/commit/7935bc87446dbc4f2a40f2bda9f3c044e853cd7e.  As mentioned above it will glitch if a fullscreen toggle is done with events in the queue, but otherwise it’s fine as a quick hack.

Now that I think of it, switching between fullscreen and windowed should maybe clear the mouse and key buffers anyway?
