### ISSUE TITLE
Revision 5265 fails to compile on Linux

### ISSUE THREAD

**Issue by DaVince** [spheredev/neosphere#28]
I get the following message:

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o obj/dyad.o -c obj/dyad.c
obj/dyad.c:1020:6: error: conflicting types for 'dyad_write'
 void dyad_write(dyad_Stream *stream, const void *data, int size) {
      ^
In file included from obj/dyad.c:37:0:
obj/dyad.h:76:6: note: previous declaration of 'dyad_write' was here
 void dyad_write(dyad_Stream *stream, void *data, int size);
      ^
scons: *** [obj/dyad.o] Error 1
scons: building terminated because of errors.
```

**Comment by fatcerberus** [comment]
Damn, it looks like the Dyad dev broke it with the recent changes.  Wouldn't be the first time I had to edit that thing.  Honestly I should just use the system sockets API directly, but Winsock and BSD sockets are _just_ different enough that a wrapper is helpful.

I'll see what I can do.

**Comment by fatcerberus** [comment]
Haha, oops, this one was on me--when I updated Dyad, it seems I forgot to update the header.  I only swapped out the .c file.  For some reason MSVC was okay with the discrepancy, but GCC correctly flagged it as a const violation.

Stupid me! :sweat_smile: Try building the latest master, it should compile now.

**Comment by DaVince** [comment]
Yep, works great now. :)
