### ISSUE TITLE
Gracefully handle lack of system directory

### ISSUE THREAD

**Issue by FlyingJester** [spheredev/neosphere#3]
minisphere currently segfaults here if no system directory is present:

main.c:141

```
    g_sys_font = al_load_font(sys_font_path, 0, 0x0);
```

A check should be put in place for the files that minisphere needs.

**Comment by fatcerberus** [comment]
This is fixed.  minisphere will now show an error box on startup and close if no system font is available.  The other system resources (windowstyle, system arrow, etc) are not strictly required and their nonexistence will cause an exception only if the corresponding GetSystemXX API is called in script.
