### ISSUE TITLE
minisphere 2.0 upcoming enhancements!

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#30]
As a version bump represents a major breaking change, I'm taking the opportunity to go crazy with 2.0.  To that end, here is a checklist of upcoming new features which will debut in the next version of minisphere:
- [x] New Sphere compiler "Cell" (see #43)
- [x] Lots of improvements to the Sphere Studio GDK plugin.
- [x] SphereFS will be standardized to ensure compatibility going forward. For starters, relative paths will always be relative to `game.sgm`.
- [x] New SphereFS compliant `FileStream` object which replaces the old RawFile API and allows more flexibility for file I/O.
- [x] ByteArray will be deprecated and any methods accepting ByteArrays will now also accept an ArrayBuffer or TypedArray.  Sphere 2.0 APIs will use ArrayBuffer/TypedArray exclusively.
- [x] Improved debugger allowing viewing local variables at any point in the call chain.

Additional ideas for enhancements can either be discussed here or in a new issue.

**Comment by DaVince** [comment]
I like these ideas. As for the package manager idea, how feasible would it be to write one as a Sphere game? I think being able to list and downloads dependencies from a GUI like that would be very beneficial for a program that is mainly graphical already.

**Comment by fatcerberus** [comment]
I imagine it wouldn't be too difficult, minisphere already includes the `~#/` path escape (see documentation) to allow stuff to be installed in the `system` directory.  That directory would have to be writable of course.  I think a better solution might be to add APIs to manage packages (not just load them).

**Comment by fatcerberus** [comment]
For the package manager, I think I want to go with a JSON format like this:

``` json
({
    "package-id": "mini-rt"
    "name": "miniRT",
    "version": "1.2.1",
    "dependencies": [
        { "package-id": "link", "version": "0.3.0" }
    ]
})
```

Sidenote: JSON is seriously overspecified.  After typing that out I want to kill whoever decided property names have to be quoted in JSON code when there is no such limitation for object literals (NOT "liberals", silly iPhone) in JS.

**Comment by fatcerberus** [comment]
The package manager specifically might need some thought put into it.  Mainly what I want to avoid is clashes between different versions of a dependent module.  For example, if miniRT depends on Link 0.3.0 but some other package depends on, say 0.4.0 which is API-incompatible, supporting both in the same game might be difficult.

Fixing this requires a tighter coupling between packages and modules, I think.  In other words, a module would have to be loaded within the context of its containing package, so that when it required the "link" module the engine would look at the package to determine the version of Link to load.

Thoughts?

**Comment by fatcerberus** [comment]
So in theory, technically minisphere 1.3+ would already run just fine from a read-only directory.  Barring loose legacy games installed in `games/` anyway.  SphereFS solves the problem handily with the `~usr/` prefix, and also by redirecting ALL writes to an SPK-packaged game into the user's home directory.

...yes, packaging in SPK is actually _superior_ in minisphere, who knew?

**Comment by fatcerberus** [comment]
minisphere 2.0 development is officially underway, see OP for details on planned features. :smile:

**Comment by fatcerberus** [comment]
Dropping the JS map engine idea; on further reflection I realize it's outside the scope of the minisphere project proper and would ultimately be better off as an independent project.

**Comment by fatcerberus** [comment]
The package manager may end up being the next thing to go; making it useful requires maintaining some sort of package server, something I don't have the resources for.

I'll experiment with the idea a bit first before striking it though, get an idea of how much work it would be to implement at least.

**Comment by fatcerberus** [comment]
minisphere 2.0 is out now, so closing this issue.
