### ISSUE TITLE
Crash on Linux when quitting game in progress in Sir Boingers

### ISSUE THREAD

**Issue by DaVince** [spheredev/neosphere#31]
When you start a game and then quit it from the pause menu, minisphere crashes with the following error:

```
Calling game()
*** Error in `bin/msphere': double free or corruption (!prev): 0x0000000001e6fb10 ***
“bin/msphere ” terminated by signal SIGABRT (Abort)
```

It happens with [this in-development version of the game](https://dl.dropboxusercontent.com/u/26026874/SirBoingers2.2b.zip).

**Comment by fatcerberus** [comment]
I suspect either a refcounting error or double finalization (which apparently can happen in Duktape).  I'll look into it.

**Comment by fatcerberus** [comment]
Hm, I can't reproduce this on Windows with minisphere 1.2.1.  I wasn't sure what you meant, so I tried both hitting Quit from the pause menu as well as closing out the engine (note: this causes a longjmp) and neither triggered a crash.  I also ran it under Application Verifier which breaks into the debugger when misbehavior happens (e.g. buffer overruns), and nada.

So it looks like this is Linux-specific, which is odd.  Just to make sure I'm doing it right, what are the exact steps to reproduce?

**Comment by DaVince** [comment]
Hitting quit from the pause menu (so while running the game) was correct. And yeah, I do believe this is Linux only. After some more testing, this bug is _odd_, however, and it seems there might be a memory leak or file handling issue. Let me elaborate.

I have since located the exact moment it happens at: the moment you enter the high score screen at all. Funny, because I fixed a crashing bug around the high score screen before, yet this one seems to be different.

In start.js:

```
this.highScoreScreen = function(levelset, allow_name_entry)
{
  ...
  this.load(levelset); //<-- The offender
```

Surely you'd think that something would be wrong in the `this.load` function for `ScoreBoard` then, right? But here's the funny thing: if I `Print("This works");` at the very end of that function, then `This works` is printed in the console. But if I print something right _after_ the `this.load(levelset);` shown above, that is never displayed. It crashes right before that.

Conclusion: for some reason, minisphere or Duktape seems to be having trouble wrapping up and finishing the `this.load` function in `ScoreBoard`. Or there is a delayed bug in the file reading stuff, I dunno.

Edit: I'm willing to gdb my way through this or whatever if you need me to, as long as you give me the instructions how. :P

**Comment by fatcerberus** [comment]
Hm, interesting.  It may well be a minisphere bug.  See, most of the underlying objects for Sphere constructs (Image, Spritesets, etc.) are refcounted.  This is necessary because a bunch of different things can hold pointers to them, both inside and outside the scope of JS (spriteset images being a great example--someone may hold onto the image even after the spriteset containing it goes away).  However two particular objects are not refcounted because I didn't think it was needed: File and RawFile.  I assume you're using the former.  In theory, a `file_t` pointer should never escape the reach of the JS engine, but if one is somehow, that would explain the crash--someone else frees the native pointer and then when Duktape runs the finalizer (the File object has gone out of scope) you get a double free.  Automatic garbage collection can be a blessing and a curse, as you see.

The only other possibility would be a Duktape bug in function call handling, but I doubt that.  Double finalization is possible, but I would think that would be reproducible on Windows too then. As for gdb, I have no idea how to use that or even how you would go about compiling the engine with debug info to make that useful (unless SCons does this already--I'm curious how it knew the crash was a double free otherwise).  I'm rather spoiled by MSVC, you see. :sweat_smile:

I'll see if I can come up with a few testcases to narrow things down.

**Comment by DaVince** [comment]
Yep, I'm using `OpenRawFile()` to read the high scores data. Hope it'll be easy enough to find.

**Comment by fatcerberus** [comment]
I found the bug!

``` c
static duk_ret_t
js_RawFile_close(duk_context* ctx)
{
    FILE* file;

    duk_push_this(ctx);
    file = duk_require_sphere_obj(ctx, -1, "RawFile");
    duk_push_pointer(ctx, NULL);
    duk_put_prop_string(ctx, -2, "\xFF" "file_ptr");  // <-- HERE (more below)
    duk_pop(ctx);
    if (file == NULL)
        duk_error_ni(ctx, -1, DUK_ERR_ERROR, "RawFile:close(): File has been closed");
    fclose(file);
    return 0;
}
```

You can see that the semantics of the RawFile object are that if the FILE pointer attached to it is NULL, the file has been closed, right?  Except that pointer is never cleared.  It does assign a NULL pointer to the internal `file_ptr` property, except that's no longer correct (it was at one time)--it should be `udata`.  When Duktape later finalizes the RawFile (at the end of the function) and does another `fclose()` on the dangling pointer, boom.

Which makes this very interesting indeed--apparently `fclose` on Windows (or at least MSVC) doesn't free the FILE pointer.  A double `fclose` in Windows-land is a completely valid thing to do, apparently.  So the runtime is leaking the file structure, how very nice of it.

Honestly the entire RawFile system needs some love.  `rawfile.c` is easily the oldest bit of code still in the minisphere codebase.  You can see that just by looking at it--there is no underlying custom structure for RawFiles like there is for every other object, everything is done within the context of the JS bindings.  It's a small glimpse into how minisphere came together so fast--I took A LOT of shortcuts in those first couple of months.  It's a wonder minisphere 1.0 was as stable as it was, really.

Anyway, I have a potential hotfix, but I want to make sure this fixes it first.  Do you know how to apply a patch with Git?  Easiest way is to save the text below to a file called `rawfile.patch` in the minisphere directory (top-level, not in `src`) and then, from a shell run `git apply rawfile.patch` on the latest source (the commit for 1.2.2):

``` patch
diff --git a/src/rawfile.c b/src/rawfile.c
index 52b2c71..7a106d4 100644
--- a/src/rawfile.c
+++ b/src/rawfile.c
@@ -161,7 +161,8 @@ js_RawFile_close(duk_context* ctx)

    duk_push_this(ctx);
    file = duk_require_sphere_obj(ctx, -1, "RawFile");
-   duk_push_pointer(ctx, NULL); duk_put_prop_string(ctx, -2, "\xFF" "file_ptr");
+   duk_push_pointer(ctx, NULL);
+   duk_put_prop_string(ctx, -2, "\xFF" "udata");
    duk_pop(ctx);
    if (file == NULL)
        duk_error_ni(ctx, -1, DUK_ERR_ERROR, "RawFile:close(): File has been closed");
```

**Comment by DaVince** [comment]
Thanks for the patch. Unfortunately, it didn't seem to work:

```
error: patch failed: src/rawfile.c:161
error: src/rawfile.c: patch does not apply
```

It was top-level, called rawfile.patch, on latest git, and I copied your exact instructions, so I'm not sure why it did that. (I also added a newline because otherwise it'd say `fatal: corrupt patch at line 14`.)

**Comment by fatcerberus** [comment]
Okay, you should be able to edit in the diff manually though, right?  It's a one-line change, just change the `"file_ptr"` in rawfile.c to `"udata"` and recompile.  Weird that the patch didn't work though.

**Comment by DaVince** [comment]
Yep, I just realized that and did it. It's fixed now! :+1:

**Comment by fatcerberus** [comment]
Oh good, I'll commit the change then.  Thanks for testing!
