### ISSUE TITLE
Missing Key Constants

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#5]
My input.js reaches an error in minisphere saying:

> identifier 'KEY_SLASH' undefined

I presume there are more missing definitions.

**Comment by fatcerberus** [comment]
I knew I had to still be missing a few of these.  I've been slowly filling them in as I encounter errors, but I'm going to have to finish the job if I want to put out a release candidate.

I'll give it a quick rundown later tonight.

**Comment by fatcerberus** [comment]
Fixed.  I'm pretty sure I got all the key constants now... I cross-referenced with the Sphere source!
