### ISSUE TITLE
Get eaten by a pig at 8:12pm

### ISSUE THREAD

**Issue by fatcerberus** [spheredev/neosphere#55]
minisphere won't be finished until everything gets eaten by a pig at 8:12pm*.  To that end, I propose feeding all the minisphere developers (which is, um, just myself) to the pig to accelerate the process.

Alternatively, we could feed the pig nuclear waste.  Since it's so big and fat, it probably won't even faze it.  And after all the nuclear waste gets eaten, THEN we feed the pig the minisphere developers.

*Note: It has to happen at 8:12pm.  Otherwise all this pig-feeding will be in vain and the pig will continue minisphere development (probably it will add features which cause the pig to come out of the screen and eat you).  And who wants that?

**Comment by marksteve** [comment]
:+1:

**Comment by fatcerberus** [comment]
There's a small issue with feeding nuclear waste to the pig, and that's that the pig wants to eat nuclear waste, but nobody else wants the pig to eat nuclear waste.  So it's more of a political issue than anything.

I guess nobody wants a radioactive pig running around trying to eat people.

**Comment by fatcerberus** [comment]
The other issue is logistical: If ALL the developers are being fed to the pig, just _who_ is going to do the pig-feeding?  Obviously it has to be somebody working on the project, which by definition makes them a developer too--and thus pig food.  This feature is harder to implement than I thought!

**Comment by marksteve** [comment]
The pig feeder can still feed himself to the pig last. That's assuming that the pig won't need much assistance.

**Comment by fatcerberus** [comment]
That's true, and considering the pig in question looks like this, I don't think it will need very much assistance:
![pig](http://i.imgur.com/v5cQHtV.jpg)

:boar: :pig_nose:

**Comment by fatcerberus** [comment]
I've decided that it's probably best if we fatten the pig up some more before feeding developers to it.  To that end, I think we should have it eat Santa Claus and 8-9 reindeer.  That should make it fat enough to eat _all_ the developers in 2 seconds.

**Comment by fatcerberus** [comment]
So it turns out I fattened the pig up _too much_ and it ran out of stuff to eat and went off to Pluto to look for space cows to munch on.  So I guess this effort is a non-starter, I'll close the issue.

Stupid pig. :pig2:
