### ISSUE TITLE
Alerting of Const in Code

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#6]
Minisphere needs a disclaimer if it reaches an error due to use of 'const' in the code. Going forward we expect to see less games using const, but at the end of the day this needs to be addressed for older games somewhere.

**Comment by fatcerberus** [comment]
Hm, short of pre-parsing the JS file with a regexp or similar, I don't know if this can be done.  Duktape reports the error as a generic "parse error", so it's impossible to distinguish from other types of syntax errors.

I think we'll just have to settle for a mention in the documentation, whenever it is I happen to get around to that. :o)

**Comment by fatcerberus** [comment]
A note about `const` has been added to the readme, so I'm going to close this now.

**Comment by fatcerberus** [comment]
Reopening to be fixed in minisphere 2.0, Duktape will be getting `const` support:
https://github.com/svaarala/duktape/pull/360
