### ISSUE TITLE
Invalid RegExp Quantifier

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#7]
How are RegExp's handled? They must differ from Spider Monkey, but then again SSFML runs the code just fine.

> invalid regexp quantifier (unknown char)

I don't have a code example because it gives me a line number, but no file.

**Comment by fatcerberus** [comment]
Hm, can't speak for regexes as I don't use them.  I assumed duktape was standards-compliant here, but perhaps not...

Unfortunately I'm all too familiar with the lack of a reported file name.  For some godforsaken reason Duktape doesn't fill in the lineNumber and fileName when it throws a SyntaxError, which leaves me with no way to retrieve it (there's no callstack).

**Comment by Radnen** [comment]
I'll try to find a minimal use example to throw up, but I'm trying to load huge game projects to see what works.

**Comment by Radnen** [comment]
I'll just leave this here. :)

``` javascript
function FormatString(s) {
    var a = arguments, i = 1;
    return s.replace(/{\?}/g, function() { return a[i++]; });
}

Abort(FormatString("Hello {?} how are you?", "John"));
```

Try it and see, it work in Sphere 1.5 and SSFML, but it lacks in minisphere. I use this all the time to do modern string concatenation, since the + method is no good in practice.

Try concatenating,

``` javascript
FormatString("{?} went to the {?} and bought {?} {?}s totaling ${?}", "Sally", "Market", 3, "Orange", 3*0.75);
```

**Comment by fatcerberus** [comment]
Interesting, the regex works in minisphere if you escape the braces:

```
function FormatString(s) {
    var a = arguments, i = 1;
    return s.replace(/\{\?\}/g, function() { return a[i++]; });
}

Abort(FormatString("Hello {?} how are you?", "John"));
```

The question now is, is this a bug in Duktape's regex parser, or is SpiderMonkey (and Jurassic) breaking standards compliance by allowing it?

**Comment by Radnen** [comment]
I put that code in the JS browser in Chrome and it worked like it should.

It also passes on: https://regex101.com/#javascript

Can't say if either method is a standards compliant test, though.

Edit: that said your method works equally as well.

**Comment by fatcerberus** [comment]
It seems Duktape is just getting confused by the braces.  Braces have special meaning in a regexp (from regular-expressions.info: "Use curly braces to specify a specific amount of repetition. Use \b[1-9][0-9]{3}\b to match a number between 1000 and 9999. \b[1-9][0-9]{2,4}\b matches a number between 100 and 99999."), but it looks like they don't need to be escaped in most engines if they are found out of their normal context.

I guess Duktape is just the odd one out here.

**Comment by fatcerberus** [comment]
I have to say, the Duktape dev is very cooperative.  Here's the conversation I had with him regarding this issue:

https://github.com/svaarala/duktape/issues/142

It seems that unescaped curly braces, while apparently legal in regexps in general, aren't valid ES5 (which only specifies a subset, apparently).  I get the impression he wants to fix it, but there's no timeline on such a fix as it requires fairly heavy under-the-hood changes to the engine.

I think I'll close this as wontfix.
