### ISSUE TITLE
GetPersonList

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#9]
I get the following

> invalid identifier 'GetPeronList'

``` javascript
(function(gpl, dp, cp, cm, me) {
    var dirty = true, list = [];

    GetPersonList = function() {
        if (dirty) { list = gpl(); dirty = false; }
        return list;
    }

    DestroyPerson = function(name) {
        dirty = true;
        dp(name);
    }

    CreatePerson = function(name, ss, die) {
        dirty = true;
        cp(name, ss, die);
    }

    ChangeMap = function(name) {
        dirty = true;
        cm(name);
    }

    MapEngine = function(name, fps) {
        dirty = true;
        me(name, fps);
    }
})(GetPersonList, DestroyPerson, CreatePerson, ChangeMap, MapEngine);
```

The above code was used to overwrite the functionality of Sphere since it was prone to crashing and this made your game run much faster. Certainly this code is not needed for all modern versions of Sphere, but GetPersonList still needs to exist.

**Comment by fatcerberus** [comment]
That's strange, GetPersonList should be implemented, I remember coding it in in the early stages of map engine development...

**Comment by Radnen** [comment]
Well it might be a scoping issue? It was only this code, which is why I posted it.

**Comment by fatcerberus** [comment]
I just pasted the above snippet into the top of Specs and it works fine.  Considering this and the missing GetMouseX(), are you sure you're using 1.0b3 for these tests?

**Comment by Radnen** [comment]
Nope, you are correct about that! :P
